name: biometric_time_tracker
description: A biometric time tracking application for companies

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^2.1.5
  http: ^1.1.0
  intl: ^0.18.1
  flutter_secure_storage: ^8.0.0
  lottie: ^2.7.0
  pdf: ^3.10.1
  csv: ^5.0.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/